module.exports = {
  'strict': [2, 'never'],
  'no-var': 2,
  'prefer-const': 2,
  'no-shadow': [2, {
    'builtinGlobals': false,
    'hoist': 'functions'
  }],
  'no-shadow-restricted-names': 2,
  'no-undef': 2,
  'no-unused-vars': [2, {
    'vars': 'local',
    'args': 'after-used'
  }],
  'no-use-before-define': 2,
  'comma-dangle': [2, 'never'],
  'no-cond-assign': [2, 'always'],
  'no-console': 1,
  'no-debugger': 1,
  'no-alert': 1,
  'no-constant-condition': 2,
  'no-dupe-keys': 2,
  'no-duplicate-case': 2,
  'no-empty': 2,
  'no-ex-assign': 2,
  'no-extra-boolean-cast': 2,
  'no-extra-semi': 2,
  'no-func-assign': 2,
  'no-inner-declarations': 2,
  'no-invalid-regexp': 2,
  'no-irregular-whitespace': 2,
  'no-obj-calls': 2,
  'no-sparse-arrays': 2,
  'no-unreachable': 2,
  'use-isnan': 2,
  'block-scoped-var': 2,
  'consistent-return': 2,
  'curly': [2, "multi"],
  'default-case': 2,
  'dot-notation': [2, {
    'allowKeywords': true
  }],
  'eqeqeq': 2,
  'guard-for-in': 2,
  'no-caller': 2,
  'no-else-return': 2,
  'no-eq-null': 2,
  'no-eval': 2,
  'no-extend-native': 2,
  'no-extra-bind': 2,
  'no-fallthrough': 2,
  'no-floating-decimal': 2,
  'no-implied-eval': 2,
  'no-lone-blocks': 2,
  'no-loop-func': 2,
  'no-multi-str': 2,
  'no-native-reassign': 2,
  'no-new': 2,
  'no-new-func': 2,
  'no-new-wrappers': 2,
  'no-octal': 2,
  'no-octal-escape': 2,
  'no-param-reassign': 2,
  'no-proto': 2,
  'no-redeclare': 2,
  'no-return-assign': 2,
  'no-script-url': 2,
  'no-self-compare': 2,
  'no-sequences': 2,
  'no-throw-literal': 2,
  'no-with': 2,
  'radix': 2,
  'vars-on-top': 2,
  'wrap-iife': [2, 'any'],
  'yoda': 2
}
